### ISSUE TITLE
Three Finger Salute - please elaborate

### ISSUE THREAD

**Issue by adrelanos** [martincmelik/Securix-Linux#84]
https://github.com/martincmelik/Securix-Linux/blob/master/securix-install/chroot.sh#L442
```
# disable "Three Finger Salute"
sed -i 's/ca\:12345/\#ca\:12345/g' /etc/inittab
```

Can you please elaborate what that is doing? Couldn't find this easily on search engines.

**Comment by martincmelik** [comment]
it should disable automatic restart via ctr+alt+delete from console
usable mainly for servers located in areas where isn't physical security on high level

another way how to restart machine or (in worst case) export some pieces of memory is "Magic SysRq key", which is disabled via sysctl

and last thing boot loader is protected by password, so you cant boot your image

there is still chance that somebody will unplug your disks and run away, so that is the reason why Securix support full disk encryption

if you're fine with that, please close it

**Comment by adrelanos** [comment]
Thanks.
